# Generated by Django 3.2.25 on 2024-03-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
